baseURL = "/"
enableRobotsTXT = true
languageCode = "en-us"
theme = "my-theme"
title = "my website"

# Pagination
paginate = 4
#paginatePath = "path"

[params]
metadescription = "website"
sharedescription = "website"
sharetitle = "website"
theme = "website"
debug = true

[taxonomies]
category = "categories"
tag = "tags"
mydate = "mydates"

[sitemap]
changefreq = "daily"
priority = 0.5
filename = "sitemap.xml"
